import React, { useState } from 'react';
import { useOpportunities, useCreateOpportunity, useUpdateOpportunity, useDeleteOpportunity, OpportunityWithRelations } from '@/hooks/useOpportunities';
import { useCountries } from '@/hooks/useCountries';
import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { Plus, Pencil, Trash2, Upload, Search } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Database } from '@/integrations/supabase/types';

type BusinessArea = Database['public']['Enums']['business_area'];
type OpportunityStatus = Database['public']['Enums']['opportunity_status'];

const businessAreas: BusinessArea[] = ['Telecom Build', 'Network Implementation', 'NOC', 'FLM', 'Resource Provisioning'];
const statuses: OpportunityStatus[] = ['Prospect', 'Qualified', 'RFP', 'Proposal', 'Negotiation', 'Won', 'Lost'];

const statusColors: Record<OpportunityStatus, string> = {
  Prospect: 'bg-slate-100 text-slate-700',
  Qualified: 'bg-blue-100 text-blue-700',
  RFP: 'bg-purple-100 text-purple-700',
  Proposal: 'bg-amber-100 text-amber-700',
  Negotiation: 'bg-orange-100 text-orange-700',
  Won: 'bg-green-100 text-green-700',
  Lost: 'bg-red-100 text-red-700',
};

const formatCurrency = (value: number) => {
  if (value >= 1000000) return `$${(value / 1000000).toFixed(1)}M`;
  if (value >= 1000) return `$${(value / 1000).toFixed(0)}K`;
  return `$${value.toFixed(0)}`;
};

const Opportunities = () => {
  const { data: opportunities, isLoading } = useOpportunities();
  const { data: countries } = useCountries();
  const { user } = useAuth();
  const createOpportunity = useCreateOpportunity();
  const updateOpportunity = useUpdateOpportunity();
  const deleteOpportunity = useDeleteOpportunity();
  const { toast } = useToast();

  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [editingOpp, setEditingOpp] = useState<OpportunityWithRelations | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [statusFilter, setStatusFilter] = useState<string>('all');

  const [formData, setFormData] = useState({
    customer_name: '',
    country_id: '',
    business_area: 'Telecom Build' as BusinessArea,
    deal_value: '',
    probability: '50',
    expected_closure_date: '',
    status: 'Prospect' as OpportunityStatus,
    notes: '',
  });

  const resetForm = () => {
    setFormData({
      customer_name: '',
      country_id: '',
      business_area: 'Telecom Build',
      deal_value: '',
      probability: '50',
      expected_closure_date: '',
      status: 'Prospect',
      notes: '',
    });
    setEditingOpp(null);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    const opportunityData = {
      customer_name: formData.customer_name,
      country_id: formData.country_id || null,
      business_area: formData.business_area,
      deal_value: parseFloat(formData.deal_value) || 0,
      probability: parseInt(formData.probability) || 0,
      expected_closure_date: formData.expected_closure_date || null,
      status: formData.status,
      notes: formData.notes || null,
      created_by: user?.id,
    };

    try {
      if (editingOpp) {
        await updateOpportunity.mutateAsync({
          id: editingOpp.id,
          updates: opportunityData,
        });
        toast({ title: 'Opportunity updated successfully' });
      } else {
        await createOpportunity.mutateAsync({
          ...opportunityData,
          opportunity_code: '', // Auto-generated by trigger
        });
        toast({ title: 'Opportunity created successfully' });
      }
      setIsDialogOpen(false);
      resetForm();
    } catch (error) {
      toast({
        title: 'Error',
        description: (error as Error).message,
        variant: 'destructive',
      });
    }
  };

  const handleEdit = (opp: OpportunityWithRelations) => {
    setEditingOpp(opp);
    setFormData({
      customer_name: opp.customer_name,
      country_id: opp.country_id || '',
      business_area: opp.business_area,
      deal_value: opp.deal_value.toString(),
      probability: opp.probability.toString(),
      expected_closure_date: opp.expected_closure_date || '',
      status: opp.status,
      notes: opp.notes || '',
    });
    setIsDialogOpen(true);
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to delete this opportunity?')) return;
    
    try {
      await deleteOpportunity.mutateAsync(id);
      toast({ title: 'Opportunity deleted successfully' });
    } catch (error) {
      toast({
        title: 'Error',
        description: (error as Error).message,
        variant: 'destructive',
      });
    }
  };

  const filteredOpportunities = opportunities?.filter(opp => {
    const matchesSearch = opp.customer_name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      opp.opportunity_code.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === 'all' || opp.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-pulse text-muted-foreground">Loading opportunities...</div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Opportunity Management</h1>
          <p className="text-muted-foreground">Manage all business opportunities across countries</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm">
            <Upload className="h-4 w-4 mr-2" />
            Import CSV
          </Button>
          <Dialog open={isDialogOpen} onOpenChange={(open) => {
            setIsDialogOpen(open);
            if (!open) resetForm();
          }}>
            <DialogTrigger asChild>
              <Button size="sm">
                <Plus className="h-4 w-4 mr-2" />
                New Opportunity
              </Button>
            </DialogTrigger>
            <DialogContent className="max-w-lg">
              <DialogHeader>
                <DialogTitle>{editingOpp ? 'Edit Opportunity' : 'Create New Opportunity'}</DialogTitle>
              </DialogHeader>
              <form onSubmit={handleSubmit} className="space-y-4">
                <div className="grid grid-cols-2 gap-4">
                  <div className="col-span-2">
                    <Label htmlFor="customer_name">Customer Name</Label>
                    <Input
                      id="customer_name"
                      value={formData.customer_name}
                      onChange={(e) => setFormData(prev => ({ ...prev, customer_name: e.target.value }))}
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="country_id">Country</Label>
                    <Select
                      value={formData.country_id}
                      onValueChange={(v) => setFormData(prev => ({ ...prev, country_id: v }))}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select country" />
                      </SelectTrigger>
                      <SelectContent className="bg-popover">
                        {countries?.map(c => (
                          <SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="business_area">Business Area</Label>
                    <Select
                      value={formData.business_area}
                      onValueChange={(v) => setFormData(prev => ({ ...prev, business_area: v as BusinessArea }))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-popover">
                        {businessAreas.map(area => (
                          <SelectItem key={area} value={area}>{area}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div>
                    <Label htmlFor="deal_value">Deal Value (USD)</Label>
                    <Input
                      id="deal_value"
                      type="number"
                      value={formData.deal_value}
                      onChange={(e) => setFormData(prev => ({ ...prev, deal_value: e.target.value }))}
                      required
                    />
                  </div>
                  <div>
                    <Label htmlFor="probability">Probability (%)</Label>
                    <Input
                      id="probability"
                      type="number"
                      min="0"
                      max="100"
                      value={formData.probability}
                      onChange={(e) => setFormData(prev => ({ ...prev, probability: e.target.value }))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="expected_closure_date">Expected Close Date</Label>
                    <Input
                      id="expected_closure_date"
                      type="date"
                      value={formData.expected_closure_date}
                      onChange={(e) => setFormData(prev => ({ ...prev, expected_closure_date: e.target.value }))}
                    />
                  </div>
                  <div>
                    <Label htmlFor="status">Status</Label>
                    <Select
                      value={formData.status}
                      onValueChange={(v) => setFormData(prev => ({ ...prev, status: v as OpportunityStatus }))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent className="bg-popover">
                        {statuses.map(status => (
                          <SelectItem key={status} value={status}>{status}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <Button type="submit" className="w-full">
                  {editingOpp ? 'Update Opportunity' : 'Create Opportunity'}
                </Button>
              </form>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="flex gap-4">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                placeholder="Search by customer or opportunity code..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-9"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="All Statuses" />
              </SelectTrigger>
              <SelectContent className="bg-popover">
                <SelectItem value="all">All Statuses</SelectItem>
                {statuses.map(status => (
                  <SelectItem key={status} value={status}>{status}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Code</TableHead>
                <TableHead>Customer</TableHead>
                <TableHead>Country</TableHead>
                <TableHead>Business Area</TableHead>
                <TableHead className="text-right">Value</TableHead>
                <TableHead className="text-center">Prob.</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Close Date</TableHead>
                <TableHead className="w-[100px]">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {filteredOpportunities?.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={9} className="text-center text-muted-foreground py-8">
                    No opportunities found
                  </TableCell>
                </TableRow>
              ) : (
                filteredOpportunities?.map((opp) => (
                  <TableRow key={opp.id}>
                    <TableCell className="font-mono text-sm">{opp.opportunity_code}</TableCell>
                    <TableCell className="font-medium">{opp.customer_name}</TableCell>
                    <TableCell>{opp.countries?.name || '-'}</TableCell>
                    <TableCell>{opp.business_area}</TableCell>
                    <TableCell className="text-right font-medium">
                      {formatCurrency(Number(opp.deal_value))}
                    </TableCell>
                    <TableCell className="text-center">{opp.probability}%</TableCell>
                    <TableCell>
                      <Badge className={statusColors[opp.status]} variant="secondary">
                        {opp.status}
                      </Badge>
                    </TableCell>
                    <TableCell>
                      {opp.expected_closure_date 
                        ? new Date(opp.expected_closure_date).toLocaleDateString()
                        : '-'}
                    </TableCell>
                    <TableCell>
                      <div className="flex gap-1">
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleEdit(opp)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="icon"
                          onClick={() => handleDelete(opp.id)}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
};

export default Opportunities;
